### ISSUE TITLE
Was there ever a solution for this?

### ISSUE THREAD

**Issue by trylks** [glenjamin/lein-new-reflection#2]
It's 2018 and apparently it still happens. Is it unavoidable? Considering that the error comes directly from the `Reflector` it may be unavoidable, but maybe it could be hidden for the code that we are not editing.

**Comment by glenjamin** [comment]
I don’t recall, the comment from #1 is still valid I think.

**Comment by trylks** [comment]
Sorry, I didn't notice the closed issues.

After further investigation:

1. The warning appears on `lein run` but not on `lein ubejar` or `lein check`
1. Introducing actual reflection problems cause errors to appear in `lein run`, `lein uberjar`, and `lein check`
1. Removing the project setting for `*warn-on-reflection*` results in no warnings on `lein run` but they still appear on `lein check` if there are actual errors in the project
1. From the previous points we can conclude that any reflection necessary for the project that makes it to the jar files generated would be catched by `lein check`
1. Removing the project setting for `*warn-on-reflection*` and doing `lein check` regularly should avoid the annoyance of leiningen warnings on `lein run` while resulting in reflection free code

So maybe do that? I will do that. HTH to future googlers https://xkcd.com/979/

Should I make a pull request so that this information is more visible in the README.md? I think it may be helpful.

**Comment by glenjamin** [comment]
Sounds like a good plan to me
